### ISSUE TITLE
def on(target: "Target") -> "Click": invalid syntax

### ISSUE THREAD

**Issue by dvu2912** [perrygoy/screenpy#1]
I got this issue while running the example code. Could you help me on this?
Traceback (most recent call last):
  File "/Users/dungvu/Downloads/appium_python_test/examples/screenpy_ex.py", line 3, in <module>
    from screenpy.actions.click import Click
  File "/Library/Python/2.7/site-packages/screenpy/actions/click.py", line 17
    def on(target: "Target") -> "Click":
                 ^
SyntaxError: invalid syntax
[Finished in 0.5s with exit code 1]

**Comment by perrygoy** [comment]
Hey @dvu2912!

This error is because you are using Python 2.7. ScreenPy is only runnable in Python3, which supports type hinting—i think that's the SyntaxError that Python2 is complaining about.
